baseURL = "/"
title = "Alvernood's"
languageCode = "en-us"
theme = "devise-off"
enableEmoji = true
googleAnalytics = "G-CMGTH927C8"
enableRobotsTXT = true
copyright = "&copy; mybae.id 2023"
#relativeURLs = true

# Main menu items
[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100
  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90


# Configuration Features
[params]
  description = "A website dedicated to coding and brain-boosting writing for hobbyists."      # Your meta description of the site
  header_title = "Alvernood"                 # Your header title
  header_subtitle = "Spending my free time tinkering with code and exploring new ways to express myself through writing." # Your header subtitle
  home_image = "/images/avatar.jpeg"          # Path to header image starting from the static directory
  recent_posts = 100                           # Max amount of recent posts to show
  mainSections = ["posts", "post", "blog"]   # Main sections to include in recent posts
  [params.style]                             # CSS style overrides
    backgroundColor = "#fff0db"
    homeImageBorderColor = "#e9f2f9"
    fontFamilyBase = "Helvetica Neue"        # First-choice font
    fontColor = "#191919"
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"          # Font Awesome icon class
    href = "https://github.com/nescatfe"      # Link to associate with icon (http://, https://, mailto:)
  [[params.social]]
    fa_icon = "fab fa-linkedin-in fa-1x"
    href = "/linkedin"
  [[params.social]]
    fa_icon = "fab fa-twitter fa-1x"
    href = "https://twitter.com/fiiascoo"
  [[params.social]]
    fa_icon = "fas fa-at fa-1x"
    href = "https://instagram.com/fajar.wh"
